### ISSUE TITLE
References through other references being produced

### ISSUE THREAD

**Issue by thewilkybarkid** [APIDevTools/json-schema-ref-parser#24]
Sorry if this is a bit confusing to understand, but I have a complicated schema with many (circular) references, and I'm using the `bundle()` method then passing the results to z-schema which can't understand it.

My main schema (minus a lot of irrelevant detail) is:
## `model.yaml`

``` yaml
$schema: http://json-schema.org/draft-04/schema#
type: object
title: Model
properties:
    body:
        type: array
        items:
            $ref: section.yaml
        minItems: 1
    body2:
        type: object
        properties:
            content:
                type: array
                items:
                    $ref: any.yaml
                minItems: 1
```

Then the following are referenced:
## `any.yaml`

``` yaml
oneOf:
  - $ref: list.yaml
  - $ref: section.yaml
  - $ref: text.yaml
```
## `list.yaml`

``` yaml
$schema: http://json-schema.org/draft-04/schema#
type: object
title: List
properties:
    items:
        type: array
        items:
            oneOf:
              - $ref: list.yaml
              - $ref: text.yaml
        minItems: 1
required:
  - items
```
## `section.yaml`

``` yaml
$schema: http://json-schema.org/draft-04/schema#
type: object
title: Section
properties:
    content:
        type: array
        items:
            $ref: any.yaml
        minItems: 1
required:
  - content
```
## `text.yaml`

``` yaml
$schema: http://json-schema.org/draft-04/schema#
type: object
title: Text
properties:
    text:
        type: string
required:
  - text
```

The `bundle()` method of this library returns:

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "title": "Model",
    "properties": {
        "body": {
            "type": "array",
            "items": {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "title": "Section",
                "properties": {
                    "content": {
                        "type": "array",
                        "items": {
                            "$ref": "#/properties/body2/properties/content/items"
                        },
                        "minItems": 1
                    }
                },
                "required": [
                    "content"
                ]
            },
            "minItems": 1
        },
        "body2": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "oneOf": [
                            {
                                "$schema": "http://json-schema.org/draft-04/schema#",
                                "type": "object",
                                "title": "List",
                                "properties": {
                                    "items": {
                                        "type": "array",
                                        "items": {
                                            "oneOf": [
                                                {
                                                    "$ref": "#/properties/body/items/properties/content/items/oneOf/0"
                                                },
                                                {
                                                    "$ref": "#/properties/body/items/properties/content/items/oneOf/2"
                                                }
                                            ]
                                        },
                                        "minItems": 1
                                    }
                                },
                                "required": [
                                    "items"
                                ]
                            },
                            {
                                "$ref": "#/properties/body/items"
                            },
                            {
                                "$schema": "http://json-schema.org/draft-04/schema#",
                                "type": "object",
                                "title": "Text",
                                "properties": {
                                    "text": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "text"
                                ]
                            }
                        ]
                    },
                    "minItems": 1
                }
            }
        }
    }
}
```

When using z-schema to parse (any) JSON it errors with:

``` json
[
    {
        "code": "UNRESOLVABLE_REFERENCE",
        "params": [
            "#/properties/body/items/properties/content/items/oneOf/0"
        ],
        "message": "Reference could not be resolved: #/properties/body/items/properties/content/items/oneOf/0",
        "path": "#/properties/body2/properties/content/items/oneOf/0/properties/items/items/oneOf/0"
    },
    {
        "code": "UNRESOLVABLE_REFERENCE",
        "params": [
            "#/properties/body/items/properties/content/items/oneOf/2"
        ],
        "message": "Reference could not be resolved: #/properties/body/items/properties/content/items/oneOf/2",
        "path": "#/properties/body2/properties/content/items/oneOf/0/properties/items/items/oneOf/1"
    }
]
```

The (first) problem is that the reference at `#/properties/body2/properties/content/items/oneOf/0/properties/items/items/oneOf/0` (`"$ref": "#/properties/body/items/properties/content/items/oneOf/0"`) goes through another `$ref`. According to https://github.com/json-schema/json-schema/wiki/$ref-traps#references-through-other-references this should still be resolvable (so the bug could be in z-schema not understanding it), but the `bundle()` method could have produced `"$ref": "#/properties/body2/properties/content/items/oneOf/0"` which would avoid the problem.

I hit this problem yesterday and reordering some properties (hence reordering some `$ref`s) fixed it a couple of times, but I can't find a way around the latest instance.
