### ISSUE TITLE
MissingPointerError: Token "smartylighting" does not exist.

### ISSUE THREAD

**Issue by KhudaDad414** [APIDevTools/json-schema-ref-parser#243]
Assume I have this JSON schema:

```
channels:
  'smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured':
    description: The topic on which measured values may be produced and consumed.
    parameters:
      streetlightId:
        description: The ID of the streetlight.
        schema:
          type: string
```
now if I try to parse the `parameters` using `$refs.get('#/channels/smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured/parameters')` I will get the above error.
Is there a way to handle cases that token(path) itself contains '/' ?
